# Generated by Django 5.0.3 on 2024-07-17 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0005_alter_mail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 7, 1, 47, 724445)),
        ),
    ]
