# Generated by Django 5.0.3 on 2024-08-18 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0006_alter_mail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 11, 1, 17, 302175)),
        ),
    ]
